name: Compile SAMP Server

on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PAWN Compiler
        run: |
          sudo apt-get update -q
          sudo apt-get install -y pawncc

      - name: Compile main.pwn
        run: |
          pawncc main.pwn \
            -i includes \
            -i pawno/include \
            -o main.amx

      - name: Upload main.amx
        uses: actions/upload-artifact@v4
        with:
          name: main-amx
          path: main.amx
